# Generated by Django 5.0.3 on 2024-03-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='otp_expiry',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
