from authapp.views.SignupView import SignupViewSet,VerifyOTPViewSet
from authapp.views.LoginView import LoginAPIView
from authapp.views.JwtAuthendication import JWTAuthenticationBackend
from authapp.views.ForgetpasswordView import ForgetPasswordRequestAPIView,ForgetPasswordConfirmAPIView